// Store data with prices
export const testStores = [
    {
        name: "Aldi Ogden Avenue",
        distance: 1.2,
        location: { lat: 41.795054238397235, lng: -88.1215363761931},
        prices: {
            flatLeafSpinach: 1.75,
            Coleslaw: 1.89,
            organicChoppedKale: 3.19,
            southwestChoppedSalad: 3.65,
            italianSalad: 2.85,
            springMix: 2.85,
            gardenSalad: 2.19,
            sweetKaleSaladKit: 3.65,
            caesarSaladKit: 3.29,
            asianChoppedSaladKit: 3.65,
            organicArugulaSpinachMix: 3.19,
            shreddedLettuce: 2.99,
            mangoSlices: 5.99,
            sweetButterSalad: 2.55,
            organicMixedGreens: 3.99,
            organicSpringMix: 5.39,
            organicBabySpinach: 3.19,
            sweetOnions: 2.99,
            carrots: 1.51,
            romaineLettuceHearts: 2.35,
            caramelApples: 3.99,
            papaya: 4.03,
            cucumber: .79,
            artisanLettuc: 3.55,
            babyCarrots: 1.19,
            autumnGrapes: 6.59,
            grannySmithApples: 3.99,
            honeyTomatoes: 3.49,
            redDeliciousApples: 2.99,
            idahoYellowPotatoes: 1.99,
            pomegranate: 2.99,
            strawberries: 2.75,
            greenPeppers: 1.50,
            pinkLadyApples: 4.29,
            organicBlackberries: 3.55,
            russetPotatoes: 1.89,
            blueberries: 2.99,
            mandarinOranges: 3.99,
            pineapple: 3.49,
            grapeTomatoes: 2.99,
            blackerries: 2.65,
            asparagus: 1.99,
            jalapenoPeppers: 0.89,
            grapeFruit: 5.49,
            organicStrawberries: 5.19,
            cauliflowerCrowns: 3.23,
            miniAvocados: 3.25,
            miniSweetPeppers: 3.36,
            anjouPears: 5.19,
            tomatoes: 2.19,
            tomatoesOnTheVine: 2.75,
            sugarSnapPeas: 2.55,
            lemons: 4.29,
            organicCeleryHearts: 2.45,
            redPotatoes: 3.95,
            organicMiniCucumbers: 3.65,
            radishes: 1.75,
            cocktailTomatoes: 4.29,
            greenOnions: 1.05,
            slicedWhiteMushrooms: 1.89,
            organicGrapeTomatoes: 3.09,
            kiwi: 4.85,
            organicBroccoli: 3.29,
            organicPinkLadyApples: 4.85,
            sweetCorn: 3.29,
            bakingPotatoes: 3.95,
            limes: 2.45,
            celery: 1.89,
            whiteOnions: 2.19,
            cherubGrapeTomatoes: 2.49,
            redOnions: 2.19,
            miniCucumbers: 1.89,
            yellowOnions: 2.65,
            ColoredPeppers: 2.99,
            organicBlueberries: 3.55,
            cilantroBunch: 0.89,
            bostonLettuce: 2.75,
            freshNavelOranges: 4.09,
            gingerRoot: 2.19,
            seedlessCucumber: 1.05,
            biteSizeYellowPotatoes: 3.65,
            yellowPotatoes: 3.95,
            raspberries: 3.65,
            caraCaraOranges: 3.19,
            organicBabyPeeledCarrots: 1.75,
            snackingTomatoesOnTheVine: 3.95,
            organicRaspberries: 4.85,
            babyBellaMushrooms: 1.99,
            brusselsSprouts: 2.55,
            icebergLettuce: 1.99,
            whiteMushrooms: 1.75,
        }
    },
    {
        name: "Jewel Osco Naperville",
        distance: 1,
        location: { lat: 41.7908, lng: -88.1233 },
        prices: {
            bread: 3.6,
            banana: 0.87,
            rice: 5.20,
            apple: .30,
        }
    },
    {
        name: "whole foods naperville",
        distance: 1,
        location: { lat: 41.7908, lng: -88.1233 },
        prices: {
            bread: 3.32,
            banana: 0.65,
            rice: 3.65,
            apple: .65,
        }
    }
]; 